### ISSUE TITLE
DeviceSize returns UnknownSize with landscape left screen

### ISSUE THREAD

**Issue by jcsobrino** [sebyddd/SDVersion#18]
I am coding with Swift language and I have notice when I rotate the iOS simulator for any iPhone model SDiPhoneVersion.deviceSize() returns UnknownSize. That only happen when I rotate to landscape left. I have tried my code with one physical iPhone and I have obtained the same mistake

**Comment by spnkr** [comment]
Same here.

**Comment by acegreen** [comment]
change deviceSize() SDiPhoneVersion.m to:

+(DeviceSize)deviceSize {
    
    CGFloat screenHeight = 0;

    if (iOSVersionGreaterThan(@"8")) {
        
        UIInterfaceOrientation orientationInterface = [[UIApplication sharedApplication]statusBarOrientation];
        
        if (orientationInterface ==  UIInterfaceOrientationPortrait)
            screenHeight = [[UIScreen mainScreen] bounds].size.height;
        
        else if ((orientationInterface == UIInterfaceOrientationLandscapeRight) || (orientationInterface == UIInterfaceOrientationLandscapeLeft))
            screenHeight = [[UIScreen mainScreen] bounds].size.width;
        
    } else
        screenHeight = [[UIScreen mainScreen] bounds].size.height;
    
    if (screenHeight == 480)
        return iPhone35inch;
    else if(screenHeight == 568)
        return iPhone4inch;
    else if(screenHeight == 667)
        return  iPhone47inch;
    else if(screenHeight == 736)
        return iPhone55inch;
    else
        return UnknownSize;
}

**Comment by sebyddd** [comment]
Fixed in 5689723c26d0122230116daafc104f9727956e9f.
