### ISSUE TITLE
todo - swift version / conversion

### ISSUE THREAD

**Issue by johndpope** [sebyddd/SDVersion#19]

**Comment by sebyddd** [comment]
John,

I wil be looking into this in the upcoming weeks, when I will find some time. 
Any pull requests are more than welcomed!

Sebastian

**Comment by sebyddd** [comment]
Due to the latest changes I decided to keep this library on Objective-C only. I will probably create a new repo with a Swift converted version.

**Comment by sebyddd** [comment]
The 3.0 launch (73a31454a362370875f3b18573f4133f7c7102f8) has full Swift 3.0 support and I think this is the correct way to do this.
