### ISSUE TITLE
OSX Compatibility 

### ISSUE THREAD

**Issue by tbaranes** [sebyddd/SDVersion#20]
That would be great to have only one library which handle both platform directly.
I don't think that would be too much work, maybe juste the project name won't fit...

What do you think? I can work on a PR if you are ok with that.

**Comment by sebyddd** [comment]
@tbaranes, I think that's a great idea. I am in holiday right now, so I can't take care of that, but it would be great if you could work on a pull-request. 

Looking forward to it! :smile:

**Comment by sebyddd** [comment]
Added in 5689723c26d0122230116daafc104f9727956e9f.
