### ISSUE TITLE
2.3 iOS pod broken

### ISSUE THREAD

**Issue by tbaranes** [sebyddd/SDVersion#26]
From the podspec:
```
  s.ios.source_files = "SDVersion/SDiOSVersion/*.{h,m}"
```

but your directory is still called `SDiPhoneVersion`, which means we don't have the iOS files in the pod:

<img width="316" alt="screen shot 2015-08-27 at 11 05 43" src="https://cloud.githubusercontent.com/assets/1402212/9516860/d9cca5fc-4cab-11e5-8ad3-da00e999c23f.png">

I didn't want to do a PR since I don't know which name you want to keep.

**Comment by dimohamdy** [comment]
please update it quickly

**Comment by sebyddd** [comment]
Fixed. CocoaPods should be back now.
