### ISSUE TITLE
ios 8 device size UIDeviceOrientationPortraitUpsideDown error

### ISSUE THREAD

**Issue by rafaelpereznajera** [sebyddd/SDVersion#27]
on ios 8 returning UnknownSize when the orientation is UIDeviceOrientationPortraitUpsideDown.

if (orientation ==  UIDeviceOrientationPortrait)
            screenHeight = [[UIScreen mainScreen] bounds].size.height;
        else if((orientation == UIDeviceOrientationLandscapeRight) || (orientation == UIInterfaceOrientationLandscapeLeft))
            screenHeight = [[UIScreen mainScreen] bounds].size.width;

UIDeviceOrientationPortraitUpsideDown is missing on the if.

**Comment by sebyddd** [comment]
Fixed in 4bf88c9ee7bd0d2116a5b5e881edf175c23f42c8.
