### ISSUE TITLE
You have iPhone 6S and 6S Plus platform strings mixed up.

### ISSUE THREAD

**Issue by kross50** [sebyddd/SDVersion#29]
For iPhone 6Plus it is 7,1 and iPhone 6 it is 7,2
BUT for iPhone 6SPlus it is 8,2 and iPhone 6S it is 8,1.

I tested this out on my 6 and 6S to validate.  Apple slightly tweaked their naming.  Hope this helps you fix your code.

CHANGE FROM:
@"iPhone8,2" :[NSNumber numberWithInteger:iPhone6S],
 @"iPhone8,1" :[NSNumber numberWithInteger:iPhone6SPlus],

TO:
@"iPhone8,1" :[NSNumber numberWithInteger:iPhone6S],
 @"iPhone8,2" :[NSNumber numberWithInteger:iPhone6SPlus],

**Comment by sebyddd** [comment]
Fixed. Thank you! :smiley:
