### ISSUE TITLE
Can't import SDVersion

### ISSUE THREAD

**Issue by acegreen** [sebyddd/SDVersion#32]
Hi,

I use cocoapods to import this library and use use_frameworks! in my Podfile

I'm not able to do

#import "SDVersion.h" in my bridging header nor am I able to import it directly in my class.

In my other project, I don't use use_frameworks! and I can import SDVersion in my bridging header.

**Comment by sebyddd** [comment]
Hmm, can you try to import the library as a framework and see if that works?

**Comment by acegreen** [comment]
I did. Import SDVersion in my class file doesn't work

**Comment by acegreen** [comment]
Can't link it as a dependency either, nor should I. I don't do it for the rest of my pods and importing them in my class file works fine.

**Comment by acegreen** [comment]
Any thoughts? Can you reproduce the issue?

**Comment by acegreen** [comment]
Ahh import SDVersion in my class file works. It was just not autocompleted for some reason.
