### ISSUE TITLE
SDiOSVersion.deviceVersion() == .iPadPro not recognized on simulator

### ISSUE THREAD

**Issue by acegreen** [sebyddd/SDVersion#33]
I do 

if SDiOSVersion.deviceVersion() == .iPadPro { 
} else {
}

else statement is executed on iPad pro simulator. How are you suppose to check device is .iPadPro on simulator? I would use screenSize but that isn't an option.

**Comment by acegreen** [comment]
I notice you have a .Simulator option but that means I need to check again .Simulator and launch an iPad Pro simulator then switch back my if statement when done

**Comment by sebyddd** [comment]
@acegreen – In 3.0.0a you should be able to check for the iPad Pro screen sizes. :)
