### ISSUE TITLE
Typo in the readme

### ISSUE THREAD

**Issue by engineeringman** [sebyddd/SDVersion#37]
Instead of:
```
      // Get device name
      NSLog(@"%@", stringFromDeviceVersion([SDVersion deviceName]));
      /* e.g: Outputs 'iPhone 6 Plus' */
```
I believe you meant to write:
```
      // Get device name
      NSLog(@"%@", stringFromDeviceVersion([SDVersion deviceVersion]));
      /* e.g: Outputs 'iPhone 6 Plus' */
```

**Comment by engineeringman** [comment]
To clarify, I meant use `deviceVersion` rather than `deviceName`

**Comment by sebyddd** [comment]
Not sure where you are seeing this. Are you seeing the latest README version? 

http://snpy.in/2CnKih

**Comment by engineeringman** [comment]
I must be losing my sanity.  I copied that straight from the readme in GitHub about 2 minutes before I logged the issue.  How could it possibly have gotten an old version?

Either way, DeviceVersionNames doesn't appear to exist.  Using the latest version (2.5.2) installed via cocoapods.  However stringFromDeviceVersion does still exist.

**Comment by sebyddd** [comment]
The readme must've been cached in your browser somehow. :)
