### ISSUE TITLE
Can't use DeviceSize enum from Swift 2.2, Xcode 7.3

### ISSUE THREAD

**Issue by cuilongzhe** [sebyddd/SDVersion#43]
Hi, @sebyddd 
After I upgrade my Xcode to 7.3, I see this new error which was fine on Xcode 7.2.1.

When I try to use DeviceSize enum, it gives me build error.
....
let screen47Value = SDiOSVersion.DeviceSize.Screen4Dot7inch.rawValue)
-> Type of 'SDiOSVersion' has no member 'DeviceSize'
....

Do you have any workaround for this issue?
Thanks.

**Comment by MaxFrax** [comment]
I have this problem too

**Comment by sebyddd** [comment]
I can't seem to be able to reproduce this. 
You should be able to compile the following: 

```
    if SDiOSVersion.deviceSize() == .Screen4Dot7inch {
            // 4.7 Inches
    }
```

Let me know if this works.
