### ISSUE TITLE
Versions on Cocoapods/Github mismatch

### ISSUE THREAD

**Issue by AzulesM** [sebyddd/SDVersion#45]
Hi @sebyddd ,

I installed SDVersion through Cocoapods which version is v2.6.
But I noticed that it actually tagged as v2.5.2 on Github.
Could you check it?
Maybe you can later release the master version that supports iPhone SE.

Thanks.

**Comment by sebyddd** [comment]
Hi @AzulesM,

Thanks for the heads up! 
A big update is coming to SDVersion soon, which will include full Swift Support, all the new devices & screen sizes as well as new features. This will also fix the version mismatch between the Pod and GitHub repo. 

Cheers! 😃

**Comment by sebyddd** [comment]
Fixed in the 3.0 launch – 73a31454a362370875f3b18573f4133f7c7102f8

Thanks! :)
