### ISSUE TITLE
Do not contains iPhone SE

### ISSUE THREAD

**Issue by yzxcool123** [sebyddd/SDVersion#46]
I use cocoapods to import SDVersion 2.6, but I found it's still not support iPhone SE, and did not contains any code about iPhone SE. I don't know why, thank you!!

**Comment by sebyddd** [comment]
Hey! This will be fixed in upcoming v3.0.0. Keep an eye on the 3.0.0a branch :).

**Comment by sebyddd** [comment]
This was fixed in the new 3.0 version. – 73a31454a362370875f3b18573f4133f7c7102f8

Please run `pod update`.
