### ISSUE TITLE
How do I get the DeviceVersionName in swift

### ISSUE THREAD

**Issue by aadjemonkeyrock** [sebyddd/SDVersion#47]
I can easily get the deviceVersion, but not the name. XCode 7 gives me DeviceVersionNames does not confirm the sequenceType

**Comment by yhkung** [comment]
You should easily get the deviceName by following code
```
let deviceName = SDiOSVersion.deviceName()
```

**Comment by AllDmeat** [comment]
That only returned device name in format like "iPhone8,1", not the "iPhone 6S". And I just can't understand how to get user-friendly device name in Swift.
