### ISSUE TITLE
README.md : MIT License link is wrong.

### ISSUE THREAD

**Issue by Jonwei** [sebyddd/SDVersion#49]
now:MIT License link is  http://http//opensource.org/licenses/mit-license.php. 
a "http//" should be removed.

**Comment by sebyddd** [comment]
I am not sure what you mean. You posted to URLs to the same License template. Why would the license link be wrong?

**Comment by Jonwei** [comment]
@sebyddd

**Comment by sebyddd** [comment]
Oh, you are talking about the README file. Fixed. Thanks for pointing it out.
