### ISSUE TITLE
3.3 causes warning because of availability

### ISSUE THREAD

**Issue by sbhhbs** [sebyddd/SDVersion#55]
Availability is meant to annotate a method is available since certain version or deprecate since certain version. 
If anyone want to annotate a device's availability, they should define their own method or macro, otherwise compile the project will cause warnings.

**Comment by SlaunchaMan** [comment]
Yep, this is a side effect of a PR I made—I’ll send a new PR today that will silence these warnings when building SDVersion. In your own code, there’s a `#pragma` you can use to silence availability warnings if you need to use the constants for old versions.

**Comment by sebyddd** [comment]
@sbhhbs – I reverted the latest commit as a temporary solution. 
@SlaunchaMan – Looking forward to that PR!

**Comment by SlaunchaMan** [comment]
@sebyddd Done!

**Comment by sebyddd** [comment]
Fixed in cbd8ae9bc094cb058885cebb34a9f6eb91b6c318 / Pod version 3.5
