### ISSUE TITLE
Screen size for iPads

### ISSUE THREAD

**Issue by geogerar** [sebyddd/SDVersion#58]
Hi,
Why we can not find screen size for iPad?
Can you fix it please?

Thanks very much

George Gerardis

**Comment by sebyddd** [comment]
@geogerar, there are no screen sizes available for targeting iPads at the moment. This is on the roadmap though. Will update you when it will be implemented.

**Comment by mrsnow-git** [comment]
when it'll be released? any plans?

**Comment by sebyddd** [comment]
Implemented in v3.0
