### ISSUE TITLE
Missing new 2016 devices 🙃

### ISSUE THREAD

**Issue by warpling** [sebyddd/SDVersion#60]
iPhone 7
WATCH 2
…

**Comment by sebyddd** [comment]
@warpling – I am still waiting for the shippings to begin so we have the confirmed device versions (platform IDs). This is surely coming very soon! 😃

**Comment by warpling** [comment]
Sounds good :) I'll add some placeholders in my fork in time being.

**Comment by warpling** [comment]
Okay good call. I tried to assume the iPhone 7 was `iPhone9,2` it is in fact `iPhone9,3` (at least my AT&T GSM one is). it appears the iPhone 7+ might be `iPhone9,2` oddly enough. Maybe the SE is now `iPhone9,1`?

**Comment by skuske** [comment]
According to https://www.theiphonewiki.com/wiki/Models

                              @"iPhone9,1" : @(iPhone7),
                              @"iPhone9,3" : @(iPhone7),
                              @"iPhone9,2" : @(iPhone7Plus),
                              @"iPhone9,4" : @(iPhone7Plus),

**Comment by sebyddd** [comment]
Added in 53719b522b0a3a2895ddc3986973b8dfe30ad161. 👍
