### ISSUE TITLE
iOS: unknown device returns 0

### ISSUE THREAD

**Issue by johnk73** [sebyddd/SDVersion#62]
SDiOSVersion.deviceVersion:101 objectForKey returns nil, then integerValue converts that into a 0
Unfortunately that's the same code as "Simulator".  Could we have a code for Unknown?

**Comment by hydyy** [comment]
same problem..... 好蛋疼

**Comment by sebyddd** [comment]
Fixed in 7703059469585a8441c618c557316df64f0ce98a.

Simulator has index 1 now. UnknownDevice is 0.
