### ISSUE TITLE
Model name for iPad 2017?

### ISSUE THREAD

**Issue by s9027059** [sebyddd/SDVersion#64]
Hello Sebastian,
Do u have any plan to support this new model?
http://www.apple.com/ipad-9.7/

Thanks

**Comment by SlaunchaMan** [comment]
I sent in a PR as #65.

**Comment by sebyddd** [comment]
Thanks @SlaunchaMan. Merged it to master: f1deb1d6abcdb31dbce0759e5b328eefbe5b3853
