### ISSUE TITLE
Watch Series 3 support

### ISSUE THREAD

**Issue by skuske** [sebyddd/SDVersion#80]
Is there any way to detect the Apple Watch Series 3?

Thanks.

**Comment by SlaunchaMan** [comment]
Check out `+deviceVersion` in the `SDwatchOSVersion.h` file—they’re all enumerated.

**Comment by skuske** [comment]
Watch Series 3 is missing...

**Comment by SlaunchaMan** [comment]
Oh, so it is! I’ll make a PR shortly.

**Comment by skuske** [comment]
Cool, thanks. Which of those Series 3 devices are the ones that support cellular? 5+6 or 7+8 ?

**Comment by skuske** [comment]
Sorry, I meant does

3,1 and 3,2

or

3,3 and 3,4

support cellular?

**Comment by SlaunchaMan** [comment]
Fixed! [Looks like](https://everymac.com/ultimate-mac-lookup/?search_keywords=Watch3*) Watch3,1 and Watch3,2 are the cellular models.
